#include "Ast.h"
#include "SymbolTable.h"
#include "Unit.h"
#include "Instruction.h"
#include "IRBuilder.h"
#include <string>
#include "Type.h"

extern FILE *yyout;
int Node::counter = 0;
IRBuilder* Node::builder = nullptr;

Node::Node()
{
    seq = counter++;
}

void Node::backPatch(std::vector<Instruction*> &list, BasicBlock*bb)
{
    for(auto &inst:list)
    {
        if(inst->isCond())
            dynamic_cast<CondBrInstruction*>(inst)->setTrueBranch(bb);
        else if(inst->isUncond())
            dynamic_cast<UncondBrInstruction*>(inst)->setBranch(bb);
    }
}

std::vector<Instruction*> Node::merge(std::vector<Instruction*> &list1, std::vector<Instruction*> &list2)
{
    std::vector<Instruction*> res(list1);
    res.insert(res.end(), list2.begin(), list2.end());
    return res;
}

void Ast::genCode(Unit *unit)
{
    IRBuilder *builder = new IRBuilder(unit);
    Node::setIRBuilder(builder);
    root->genCode();
}

void FunctionDef::genCode()
{
    Unit *unit = builder->getUnit();
    Function *func = new Function(unit, se);
    BasicBlock *entry = func->getEntry();
    // set the insert point to the entry basicblock of this function.
    builder->setInsertBB(entry);

    stmt->genCode();

    /**
     * Construct control flow graph. You need do set successors and predecessors for each basic block.
     * Todo
    */
   
}

void BinaryExpr::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Function *func = bb->getParent();
    if (op == AND)
    {
        BasicBlock *trueBB = new BasicBlock(func);  // if the result of lhs is true, jump to the trueBB.
        expr1->genCode();
        backPatch(expr1->trueList(), trueBB);
        builder->setInsertBB(trueBB);               // set the insert point to the trueBB so that intructions generated by expr2 will be inserted into it.
        expr2->genCode();
        true_list = expr2->trueList();
        false_list = merge(expr1->falseList(), expr2->falseList());
    }
    else if(op == OR)
    {
        // Todo
        BasicBlock* trueBB = new BasicBlock(func);
        expr1->genCode();
        backPatch(expr1->falseList(), trueBB);
        builder->setInsertBB(trueBB);
        expr2->genCode();
        true_list = merge(expr1->trueList(), expr2->trueList());
        false_list = expr2->falseList();
    }
    else if(op >= LESS && op <= GREATER)
    {
        // Todo
    }
    else if(op >= ADD && op <= MOD)
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case ADD:
            opcode = BinaryInstruction::ADD;
            break;
        case SUB:
            opcode = BinaryInstruction::SUB;
            break;
        case MUL:
            opcode = BinaryInstruction::MUL;
            break;
        case DIV:
            opcode = BinaryInstruction::DIV;
            break;
        case MOD:
            opcode = BinaryInstruction::MOD;
            break;
        }
        new BinaryInstruction(opcode, dst, src1, src2, bb);
    }
}

void Constant::genCode()
{
    // we don't need to generate code.
}

void Id::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getAddr();
    new LoadInstruction(dst, addr, bb);
}

void IfStmt::genCode()
{
    Function *func;
    BasicBlock *then_bb, *end_bb;

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), end_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    builder->setInsertBB(end_bb);
}

void IfElseStmt::genCode()
{
    // Todo
}

void CompoundStmt::genCode()
{
    // Todo
}

void SeqNode::genCode()
{
    // Todo
}

void DeclStmt::genCode()
{
    IdentifierSymbolEntry *se = dynamic_cast<IdentifierSymbolEntry *>(id->getSymPtr());
    if(se->isGlobal())
    {
        Operand *addr;
        SymbolEntry *addr_se;
        addr_se = new IdentifierSymbolEntry(*se);
        addr_se->setType(new PointerType(se->getType()));
        addr = new Operand(addr_se);
        se->setAddr(addr);
    }
    else if(se->isLocal())
    {
        Function *func = builder->getInsertBB()->getParent();
        BasicBlock *entry = func->getEntry();
        Instruction *alloca;
        Operand *addr;
        SymbolEntry *addr_se;
        Type *type;
        type = new PointerType(se->getType());
        addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());
        addr = new Operand(addr_se);
        alloca = new AllocaInstruction(addr, se);                   // allocate space for local id in function stack.
        entry->insertFront(alloca);                                 // allocate instructions should be inserted into the begin of the entry block.
        se->setAddr(addr);                                          // set the addr operand in symbol entry so that we can use it in subsequent code generation.
    }
}

void ReturnStmt::genCode()
{
    // Todo
}

void AssignStmt::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    expr->genCode();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(lval->getSymPtr())->getAddr();
    Operand *src = expr->getOperand();
    /***
     * We haven't implemented array yet, the lval can only be ID. So we just store the result of the `expr` to the addr of the id.
     * If you want to implement array, you have to caculate the address first and then store the result into it.
     */
    new StoreInstruction(addr, src, bb);
}

void UnaryExpr::genCode() {

}

void DeclStmts::genCode() {
    for (long unsigned int i = 0; i < declStmts.size(); ++i) {
        StmtNode *declStmt=declStmts.front();
        declStmts.pop();
        dynamic_cast<DeclStmt*>(declStmt)->genCode();
        declStmts.push(declStmt);
    }
}

void WhileStmt::genCode() {

}

void FuncRParamExpr::genCode() {

}

void CallExpr::genCode() {

}

void ExprStmt::genCode() {

}

void Ast::typeCheck()
{
    if(root != nullptr)
        root->typeCheck();
}

void FunctionDef::typeCheck()
{
    // Todo


}

void BinaryExpr::typeCheck()
{
    // Todo
    Type *type1 = expr1->getSymPtr()->getType();
    Type *type2 = expr2->getSymPtr()->getType();
    if(type1 != type2)
    {
        fprintf(stderr, "type %s and %s mismatch in line xx",type1->toStr().c_str(), type2->toStr().c_str());
        exit(EXIT_FAILURE);
    }
    symbolEntry->setType(type1);

}

void Constant::typeCheck()
{
    // Todo
    return;
}

void Id::typeCheck()
{
    // Todo
    return;
}

void IfStmt::typeCheck()
{
    // Todo
    if(!this->cond) {
        fprintf(stderr, "no cond expr in IfStmt");
        exit(EXIT_FAILURE);
    }
    if(!this->thenStmt){
        fprintf(stderr, "no then stmt in IfStmt");
        exit(EXIT_FAILURE);
    }
    cond->typeCheck();
    thenStmt->typeCheck();
    this->setNodeType(thenStmt->getNodeType());
}

void IfElseStmt::typeCheck(){
    // Todo
    if(!this->cond) {
        fprintf(stderr, "no cond expr in IfStmt");
        exit(EXIT_FAILURE);
    }
    if(!this->thenStmt){
        fprintf(stderr, "no then stmt in IfStmt");
        exit(EXIT_FAILURE);
    }
    if(!this->elseStmt){
        fprintf(stderr, "no else stmt in IfStmt");
        exit(EXIT_FAILURE);
    }
    cond->typeCheck();
    thenStmt->typeCheck();
    elseStmt->typeCheck();

    Type*type1=thenStmt->getNodeType();
    Type*type2=elseStmt->getNodeType();
    if (type1== nullptr){
        this->setNodeType(type2);
    }else if(type2== nullptr){
        this->setNodeType(type1);
    }else{
        if (type1==type2){
            this->setNodeType(type1);
        }else{
            if((type1->isFloat()&&type2->isInt())||
                    (type1->isInt()&&type2->isFloat())){
                this->setNodeType(type1->isFloat()?type1:type2);
            }else{
                fprintf(stderr, "type %s and %s mismatch in line xx",type1->toStr().c_str(), type2->toStr().c_str());
                exit(EXIT_FAILURE);
            }
        }
    }
}

void CompoundStmt::typeCheck(){
    // Todo
    if(!stmt){
        fprintf(stderr, "no stmt in CompoundStmt");
        exit(EXIT_FAILURE);
    }
    stmt->typeCheck();
    this->setNodeType(stmt->getNodeType());
}

void SeqNode::typeCheck()
{
    // Todo
    if(!this->stmt1){
        fprintf(stderr, "no stmt1 in SeqNode");
        exit(EXIT_FAILURE);
    }
    if(!this->stmt2){
        fprintf(stderr, "no stmt2 in SeqNode");
        exit(EXIT_FAILURE);
    }
    stmt1->typeCheck();
    stmt2->typeCheck();

    Type*type1=stmt1->getNodeType();
    Type*type2=stmt2->getNodeType();

    if (type1== nullptr){
        this->setNodeType(type2);
    }else if(type2== nullptr){
        this->setNodeType(type1);
    }else{
        if (type1==type2){
            this->setNodeType(type1);
        }else{
            if((type1->isFloat()&&type2->isInt())||
               (type1->isInt()&&type2->isFloat())){
                this->setNodeType(type1->isFloat()?type1:type2);
            }else{
                fprintf(stderr, "type %s and %s mismatch in line xx",type1->toStr().c_str(), type2->toStr().c_str());
                exit(EXIT_FAILURE);
            }
        }
    }
}

void DeclStmt::typeCheck()
{
    // Todo
}

void ReturnStmt::typeCheck()
{
    // Todo
    if (retValue== nullptr)
        return;
    this->setNodeType(retValue->getSymPtr()->getType());
}

void AssignStmt::typeCheck()
{
    // Todo
    if (lval== nullptr){
        // throw errors
    }
    if (expr== nullptr){
        //throw errors
    }
    Type*type1=lval->getSymPtr()->getType();
    Type*type2=expr->getSymPtr()->getType();

}

void UnaryExpr::typeCheck() {
    if (expr== nullptr){
        // throw errors
    }
}

void DeclStmts::typeCheck() {
    if(declStmts.empty()){
        fprintf(stderr, "no declStmt in DeclStmts");
        exit(EXIT_FAILURE);
    }
    for (long unsigned int i = 0; i < declStmts.size(); ++i) {
        StmtNode *declStmt=declStmts.front();
        declStmts.pop();
        dynamic_cast<DeclStmt*>(declStmt)->typeCheck();
        declStmts.push(declStmt);
    }
}

void WhileStmt::typeCheck() {
    if (cond== nullptr){
        fprintf(stderr, "no cond in WhileStmt");
        exit(EXIT_FAILURE);
    }
    if (stmt== nullptr){
        fprintf(stderr, "no stmt in WhileStmt");
        exit(EXIT_FAILURE);
    }
    this->setNodeType(stmt->getNodeType());
}

void FuncRParamExpr::typeCheck() {
    // TODO:check if RParams match corresponding FParams

}

void CallExpr::typeCheck() {
    if (params!= nullptr)
        params->typeCheck();
}

void ExprStmt::typeCheck() {
    if (expr!= nullptr)
        expr->typeCheck();
}

void BinaryExpr::output(int level)
{
    std::string op_str;
    switch(op)
    {
        case ADD:
            op_str = "add";
            break;
        case SUB:
            op_str = "sub";
            break;
        case AND:
            op_str = "and";
            break;
        case OR:
            op_str = "or";
            break;
        case EQ:
            op_str = "equal";
            break;
        case NEQ:
            op_str = "unequal";
            break;
        case LESS:
            op_str = "less";
            break;
        case LESSEQ:
            op_str = "less equal";
            break;
        case GREATER:
            op_str = "greater";
            break;
        case GREATEREQ:
            op_str = "greater equal";
            break;
        case MUL:
            op_str = "mul";
            break;
        case DIV:
            op_str = "div";
            break;
        case MOD:
            op_str = "mod";
            break;
    }
    fprintf(yyout, "%*cBinaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr1->output(level + 4);
    expr2->output(level + 4);
}

void Ast::output()
{
    fprintf(yyout, "program\n");
    if(root != nullptr)
        root->output(4);
}

void UnaryExpr::output(int level)
{
    std::string op_str;
    switch(op)
    {
        case ADD:
            op_str = "plus";
            break;
        case SUB:
            op_str = "uminus";
            break;
        case NOT:
            op_str = "not";
            break;
    }
    fprintf(yyout, "%*cUnaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr->output(level + 4);
}

void Constant::output(int level)
{
    std::string type, value;
    type = symbolEntry->getType()->toStr();
    value = symbolEntry->toStr();
    fprintf(yyout, "%*cIntegerLiteral\tvalue: %s\ttype: %s\n", level, ' ',
            value.c_str(), type.c_str());
}

void Id::output(int level)
{
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
    fprintf(yyout, "%*cId\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
}

void CompoundStmt::output(int level)
{
    fprintf(yyout, "%*cCompoundStmt\n", level, ' ');
    if(nullptr!=stmt)
        stmt->output(level + 4);
}

void SeqNode::output(int level)
{
    if(nullptr!=stmt1)
        stmt1->output(level);
    if(nullptr!=stmt1)
        stmt2->output(level);
}

void DeclStmt::output(int level)
{
    fprintf(yyout, "%*cDeclStmt\n", level, ' ');
    id->output(level + 4);
    if(nullptr!=expr){
        expr->output(level+4);
    }
}

Id *DeclStmt::getId() const{
    return id;
}

void IfStmt::output(int level)
{
    fprintf(yyout, "%*cIfStmt\n", level, ' ');
    if(nullptr!=cond)
        cond->output(level + 4);
    if(nullptr!=thenStmt)
        thenStmt->output(level + 4);
}

void IfElseStmt::output(int level)
{
    fprintf(yyout, "%*cIfElseStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
    elseStmt->output(level + 4);
}

void ReturnStmt::output(int level)
{
    fprintf(yyout, "%*cReturnStmt\n", level, ' ');
    retValue->output(level + 4);
}

void AssignStmt::output(int level)
{
    fprintf(yyout, "%*cAssignStmt\n", level, ' ');
    lval->output(level + 4);
    expr->output(level + 4);
}

void FunctionDef::output(int level)
{
    std::string name, type;
    name = se->toStr();
    type = se->getType()->toStr();
    fprintf(yyout, "%*cFunctionDefine function name: %s, type: %s\n", level, ' ', 
            name.c_str(), type.c_str());
    if (nullptr!=decl)
        decl->output(level + 4);
    stmt->output(level + 4);
}

void DeclStmts::insertDeclStmt(StmtNode *declStmt) {
    declStmts.push(declStmt);
}

void DeclStmts::output(int level) {
    fprintf(yyout, "%*cDeclStmts\n", level, ' ');
    while (declStmts.size()){
        StmtNode *declStmt=declStmts.front();
        declStmt->output(level + 4);
        declStmts.pop();
    }
}

std::vector<SymbolEntry *> DeclStmts::getId() {
    std::vector<SymbolEntry *> symbolEntry;
    if(declStmts.empty()){
        return symbolEntry;
    }
    for (long unsigned int i = 0; i < declStmts.size(); ++i) {
        StmtNode *declStmt=declStmts.front();
        declStmts.pop();
        symbolEntry.push_back(dynamic_cast<DeclStmt*>(declStmt)->
                getId()->getSymbolEntry());
        declStmts.push(declStmt);
    }
    return symbolEntry;
}

void WhileStmt::output(int level) {
    fprintf(yyout, "%*cWhileStmt\n", level, ' ');
    cond->output(level + 4);
    stmt->output(level + 4);
}

SymbolEntry *ExprNode::getSymbolEntry() const {
    return symbolEntry;
}

void FuncRParamExpr::output(int level) {
    fprintf(yyout, "%*cFuncRParamExpr\n", level, ' ');
    for (long unsigned int i = 0; i < params.size(); ++i) {
        ExprNode* param=params[i];
        param->output(level + 4);
    }
}

void FuncRParamExpr::insertParam(ExprNode *Exp) {
    params.push_back(Exp);
}

void CallExpr::output(int level) {
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
    fprintf(yyout, "%*cCallExpr\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
    if (nullptr!=params)
        params->output(level+4);
}

void ExprStmt::output(int level) {
    expr->output(level);
}


